In [1]:
import torch
import torch.nn as nn

/opt/conda/envs/ldm/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## 一、Pytorch基本操作考察

1.使用 𝐓𝐞𝐧𝐬𝐨𝐫 初始化一个 𝟏×𝟑 的矩阵 𝑴 和一个 𝟐×𝟏 的矩阵 𝑵，对两矩阵进行减法操作（要求实现三种不同的形式），给出结果并分析三种方式的不同（如果出现报错，分析报错的原因），同时需要指出在计算过程中发生了什么

In [2]:
M = torch.randn(1, 3)
N = torch.randn(2, 1)

print(M - N)
print(torch.sub(M, N))
print(M.sub(N))

tensor([[-1.0299, -0.7920, -1.3551],
        [-0.9191, -0.6811, -1.2443]])
tensor([[-1.0299, -0.7920, -1.3551],
        [-0.9191, -0.6811, -1.2443]])
tensor([[-1.0299, -0.7920, -1.3551],
        [-0.9191, -0.6811, -1.2443]])


In [3]:
print(M.sub_(N)) # 会报错

RuntimeError: output with shape [1, 3] doesn't match the broadcast shape [2, 3]

2.① 利用 𝐓𝐞𝐧𝐬𝐨𝐫 创建两个大小分别 𝟑×𝟐 和 𝟒×𝟐 的随机数矩阵 𝑷 和 𝑸 ，要求服从均值为0，标准差0.01为的正态分布；② 对第二步得到的矩阵 𝑸 进行形状变换得到 𝑸 的转置 𝑸^𝑻 ；③ 对上述得到的矩阵 𝑷 和矩阵 𝑸^𝑻 求矩阵相乘.

In [4]:
P = torch.normal(0, 0.01, (3, 2))
Q = torch.normal(0, 0.01, (4, 2))
print('P:', P)
print('Q:', Q)
Q_T = Q.T
print('Q_T:', Q_T)
print('P@Q_T:', P@Q_T)
print('P.mm(Q_T):', P.mm(Q_T))

P: tensor([[ 0.0023,  0.0134],
        [ 0.0125,  0.0088],
        [ 0.0066, -0.0122]])
Q: tensor([[ 0.0065, -0.0206],
        [ 0.0102,  0.0080],
        [-0.0160, -0.0124],
        [-0.0030, -0.0214]])
Q_T: tensor([[ 0.0065,  0.0102, -0.0160, -0.0030],
        [-0.0206,  0.0080, -0.0124, -0.0214]])
P@Q_T: tensor([[-2.6106e-04,  1.2988e-04, -2.0217e-04, -2.9347e-04],
        [-1.0016e-04,  1.9681e-04, -3.0855e-04, -2.2538e-04],
        [ 2.9445e-04, -3.0432e-05,  4.5649e-05,  2.4194e-04]])
P.mm(Q_T): tensor([[-2.6106e-04,  1.2988e-04, -2.0217e-04, -2.9347e-04],
        [-1.0016e-04,  1.9681e-04, -3.0855e-04, -2.2538e-04],
        [ 2.9445e-04, -3.0432e-05,  4.5649e-05,  2.4194e-04]])


3.给定公式 $𝑦_3=𝑦_1+𝑦_2=𝑥^2+𝑥^3$，且 $𝑥=1$。利用学习所得到的Tensor的相关知识，求$𝑦_3$对$𝑥$的梯度，即$(𝑑𝑦_3)/𝑑𝑥$。
要求在计算过程中，在计算$𝑥^3$ 时中断梯度的追踪，观察结果并进行原因分析。提示, 可使用 with torch.no_grad()

In [5]:
# 设置 x 的值为 1，并要求梯度计算
x = torch.tensor(1.0, requires_grad=True)

y1 = x**2

# 使用 with torch.no_grad() 计算 y2 = x^3，中断梯度追踪
with torch.no_grad():
    y2 = x**3

y3 = y1 + y2

# 计算 y3 对 x 的梯度
y3.backward()

# 打印结果
print(f"x = {x}")
print(f"y3 = {y3}")
print(f"dy3/dx = {x.grad}")

x = 1.0
y3 = 2.0
dy3/dx = 2.0
